# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [9]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

In [10]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [12]:
df.columns = df.columns.str.lower().str.replace(" ", "_")  # first to uniformizing columns' names

low_claim_yes = df[
    (df["total_claim_amount"] < 1000) &
    (df["response"] == "Yes")
]

low_claim_yes.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [13]:
low_claim_yes.shape

(1399, 26)

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [14]:
#filter who answered "yes"
yes_df = df[df["response"] == "Yes"]

In [15]:
#calculating mean by policy_type and gender
agg_yes = yes_df.groupby(["policy_type", "gender"]).agg(
    avg_monthly_premium=("monthly_premium_auto", "mean"),
    avg_clv=("customer_lifetime_value", "mean"),
    avg_total_claim=("total_claim_amount", "mean")
).reset_index()

agg_yes

      policy_type gender  avg_monthly_premium      avg_clv  avg_total_claim
0  Corporate Auto      F            94.301775  7712.628736       433.738499
1  Corporate Auto      M            92.188312  7944.465414       408.582459
2   Personal Auto      F            98.998148  8339.791842       452.965929
3   Personal Auto      M            91.085821  7448.383281       457.010178
4    Special Auto      F            92.314286  7691.584111       453.280164
5    Special Auto      M            86.343750  8247.088702       429.527942

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [16]:
customers_by_state = df.groupby("state").agg(
    num_customers=("customer", "count")
).reset_index()

customers_by_state

        state  num_customers
0     Arizona           1937
1  California           3552
2      Nevada            993
3      Oregon           2909
4  Washington            888

In [17]:
#  filtering states where more than 500 customers
big_states = customers_by_state[customers_by_state["num_customers"] > 500]
big_states

        state  num_customers
0     Arizona           1937
1  California           3552
2      Nevada            993
3      Oregon           2909
4  Washington            888

#insights:
those are the states with higher number of customers, and where the company should invest more time and resources, bc there is where the potential for profit is higher

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [18]:
clv_stats = df.groupby(["education", "gender"]).agg(
    clv_min=("customer_lifetime_value", "min"),
    clv_max=("customer_lifetime_value", "max"),
    clv_median=("customer_lifetime_value", "median")
).reset_index()

clv_stats

              education gender      clv_min      clv_max   clv_median
0              Bachelor      F  1904.000852  73225.95652  5640.505303
1              Bachelor      M  1898.007675  67907.27050  5548.031892
2               College      F  1898.683686  61850.18803  5623.611187
3               College      M  1918.119700  61134.68307  6005.847375
4                Doctor      F  2395.570000  44856.11397  5332.462694
5                Doctor      M  2267.604038  32677.34284  5577.669457
6  High School or Below      F  2144.921535  55277.44589  6039.553187
7  High School or Below      M  1940.981221  83325.38119  6286.731006
8                Master      F  2417.777032  51016.06704  5729.855012
9                Master      M  2272.307310  50568.25912  5579.099207

#insights:
Customers with High School or Below show the highest median CLV, especially men — this segment has strong long‑term value.

The Bachelor and College groups have stable and predictable CLV, making them low‑risk and easy to target.

Doctor and Master customers show lower maximum CLV, suggesting limited upside potential.

Across almost all education levels, men have slightly higher median CLV than women.

Education level does not drastically change median CLV

The High School or Below (M) segment has the largest CLV range, indicating both high‑value and low‑value customers

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [20]:
df["effective_to_date"] = pd.to_datetime(df["effective_to_date"])
df["month"] = df["effective_to_date"].dt.month_name()

In [22]:
policies_by_state_month = df.groupby(["state", "month"]).agg(
    policies_sold=("policy", "count")
).reset_index()

policies_by_state_month.head()

        state     month  policies_sold
0     Arizona  February            929
1     Arizona   January           1008
2  California  February           1634
3  California   January           1918
4      Nevada  February            442

In [23]:
table_state_month = policies_by_state_month.pivot(
    index="state",
    columns="month",
    values="policies_sold"
).fillna(0)

table_state_month

month       February  January
state
Arizona          929     1008
California      1634     1918
Nevada           442      551
Oregon          1344     1565
Washington       425      463

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [24]:
total_policies_by_state = policies_by_state_month.groupby("state")["policies_sold"].sum().reset_index()

top3_states = total_policies_by_state.sort_values("policies_sold", ascending=False).head(3)
top3_states

        state  policies_sold
1  California           3552
3      Oregon           2909
0     Arizona           1937

In [25]:
top3_names = top3_states["state"].tolist()

top3_policies_by_state_month = policies_by_state_month[
    policies_by_state_month["state"].isin(top3_names)
]

top3_table = top3_policies_by_state_month.pivot(
    index="state",
    columns="month",
    values="policies_sold"
).fillna(0)

top3_table

month       February  January
state
Arizona          929     1008
California      1634     1918
Oregon          1344     1565

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [26]:
channel_response = df.groupby("sales_channel").agg(
    total_customers=("customer", "count"),
    yes_customers=("response", lambda x: (x == "Yes").sum())
).reset_index()

channel_response["yes_rate"] = channel_response["yes_customers"] / channel_response["total_customers"]

channel_response

  sales_channel  total_customers  yes_customers  yes_rate
0         Agent             4121            742  0.180053
1        Branch             3022            326  0.107876
2   Call Center             2141            221  0.103223
3           Web             1626            177  0.108856